export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'

export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'
export const GET_PROFILE_RESET = 'GET_PROFILE_RESET'

export const GET_PROFILE_BY_ID_REQUEST = 'GET_PROFILE_BY_ID_REQUEST'
export const GET_PROFILE_BY_ID_SUCCESS = 'GET_PROFILE_BY_ID_SUCCESS'
export const GET_PROFILE_BY_ID_FAIL = 'GET_PROFILE_BY_ID_FAIL'
export const GET_PROFILE_BY_ID_RESET = 'GET_PROFILE_BY_ID_RESET'

export const GET_ALL_PROFILE_REQUEST = 'GET_ALL_PROFILE_REQUEST'
export const GET_ALL_PROFILE_SUCCESS = 'GET_ALL_PROFILE_SUCCESS'
export const GET_ALL_PROFILE_FAIL = 'GET_ALL_PROFILE_FAIL'

export const FOLLOW_PROFILE_REQUEST = 'FOLLOW_PROFILE_REQUEST'
export const FOLLOW_PROFILE_SUCCESS = 'FOLLOW_PROFILE_SUCCESS'
export const FOLLOW_PROFILE_FAIL = 'FOLLOW_PROFILE_FAIL'

export const UNFOLLOW_PROFILE_REQUEST = 'UNFOLLOW_PROFILE_REQUEST'
export const UNFOLLOW_PROFILE_SUCCESS = 'UNFOLLOW_PROFILE_SUCCESS'
export const UNFOLLOW_PROFILE_FAIL = 'UNFOLLOW_PROFILE_FAIL'

export const ISFOLLOW_PROFILE_REQUEST = 'ISFOLLOW_PROFILE_REQUEST'
export const ISFOLLOW_PROFILE_SUCCESS = 'ISFOLLOW_PROFILE_SUCCESS'
export const ISFOLLOW_PROFILE_FAIL = 'ISFOLLOW_PROFILE_FAIL'
export const ISFOLLOW_PROFILE_RESET = 'ISFOLLOW_PROFILE_RESET'
