export const GET_MY_POSTS_REQUEST = 'GET_MY_POSTS_REQUEST'
export const GET_MY_POSTS_SUCCESS = 'GET_MY_POSTS_SUCCESS'
export const GET_MY_POSTS_FAIL = 'GET_MY_POSTS_FAIL'
export const GET_MY_POST_RESET = 'GET_MY_POST_RESET'

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'

export const DELETE_LIKE_POST_REQUEST = 'DELETE_LIKE_POST_REQUEST'
export const DELETE_LIKE_POST_SUCCESS = 'DELETE_LIKE_POST_SUCCESS'
export const DELETE_LIKE_POST_FAIL = 'DELETE_LIKE_POST_FAIL'

export const COMMENT_POST_REQUEST = 'COMMENT_POST_REQUEST'
export const COMMENT_POST_SUCCESS = 'COMMENT_POST_SUCCESS'
export const COMMENT_POST_FAIL = 'COMMENT_POST_FAIL'

export const GET_COMMENTS_POST_REQUEST = 'GET_COMMENTS_POST_REQUEST'
export const GET_COMMENTS_POST_SUCCESS = 'GET_COMMENTS_POST_SUCCESS'
export const GET_COMMENTS_POST_FAIL = 'GET_COMMENTS_POST_FAIL'
export const GET_COMMENTS_POST_RESET = 'GET_COMMENTS_POST_RESET'

export const ADD_POST_REQUEST = 'ADD_POST_REQUEST'
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS'
export const ADD_POST_FAIL = 'ADD_POST_FAIL'

export const GET_ANY_POST_REQUEST = 'GET_ANY_POST_REQUEST'
export const GET_ANY_POST_SUCCESS = 'GET_ANY_POST_SUCCESS'
export const GET_ANY_POST_FAIL = 'GET_ANY_POST_FAIL'
export const GET_ANY_POST_RESET = 'GET_ANY_POST_RESET'

export const GET_POSTS_BY_PROFILE_REQUEST = 'GET_POSTS_BY_PROFILE_REQUEST'
export const GET_POSTS_BY_PROFILE_SUCCESS = 'GET_POSTS_BY_PROFILE_SUCCESS'
export const GET_POSTS_BY_PROFILE_FAIL = 'GET_POSTS_BY_PROFILE_FAIL'
export const GET_POSTS_BY_PROFILE_RESET = 'GET_POSTS_BY_PROFILE_RESET'

export const GET_POSTS_FOR_HOME_REQUEST = 'GET_POSTS_FOR_HOME_REQUEST'
export const GET_POSTS_FOR_HOME_SUCCESS = 'GET_POSTS_FOR_HOME_SUCCESS'
export const GET_POSTS_FOR_HOME_FAIL = 'GET_POSTS_FOR_HOME_FAIL'
export const GET_POSTS_FOR_HOME_RESET = 'GET_POSTS_FOR_HOME_RESET'

export const ISLIKED_POST_REQUEST = 'ISLIKED_POST_REQUEST'
export const ISLIKED_POST_SUCCESS = 'ISLIKED_POST_SUCCESS'
export const ISLIKED_POST_FAIL = 'ISLIKED_POST_FAIL'

export const DELETE_COMMENT_POST_REQUEST = 'DELETE_COMMENT_POST_REQUEST'
export const DELETE_COMMENT_POST_SUCCESS = 'DELETE_COMMENT_POST_SUCCESS'
export const DELETE_COMMENT_POST_FAIL = 'DELETE_COMMENT_POST_FAIL'
